#!/usr/bin/env python
# host = "cs5700f16.ccs.neu.edu"
# neuID = "001970749"

import socket
import sys
import getopt

def calculate(buff):
    num1 = float(buff[2])
    num2 = float(buff[4])

    sol = 0
    if buff[3] is "+":
        sol = num1 + num2
    if buff[3] is "-":
        sol = num1 - num2
    if buff[3] is "*":
        sol = num1 * num2
    if buff[3] is "/":
        sol = num1 / num2
    return sol

def sendAndReceive(buff):
    sol = calculate(buff)
    msg = "cs3700fall2017 " + str(int(sol)) + "\n"
    s.sendall(msg)
    data = s.recv(1024)
    return data.split()

# Begin
optlist, args = getopt.getopt(sys.argv[1:], 'p:')
if len(args) != 2:
    print "Incorrect arguments"
    exit()

s = socket.socket()
host = args[0]
neuID = args[1]
port = 27998

for o, v in optlist:
    if o == "-p":
        port = int(v)

s.connect((host, port))
s.sendall("cs3700fall2017 HELLO 001970749\n")
data = s.recv(1024)
buff = data.split()
while buff[1] == "STATUS":
    buff = sendAndReceive(buff)

print buff[1]
s.close
